version: '3.3'
services:
  app_dev:
    container_name: payment_service_dev
    build: .
    ports:
      - 127.0.0.1:9000:9000
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - db_dev
    links:
      - db_dev
  db_dev:
    image: mysql:5.7
    ports:
      - "127.0.0.1:3305:3305"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "photobooth"
      MYSQL_PASSWORD: "photobooth123"
      MYSQL_DATABASE: "project"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
